-- MySQL Script generated by MySQL Workbench
-- Sun Apr 15 19:33:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema VotacionesUnimag
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema VotacionesUnimag
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VotacionesUnimag` DEFAULT CHARACTER SET utf8 ;
USE `VotacionesUnimag` ;

-- -----------------------------------------------------
-- Table `VotacionesUnimag`.`Facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VotacionesUnimag`.`Facultad` (
  `idFacultad` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idFacultad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VotacionesUnimag`.`Programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VotacionesUnimag`.`Programa` (
  `idPrograma` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `Facultad_idFacultad` INT NOT NULL,
  PRIMARY KEY (`idPrograma`),
  INDEX `fk_Programa_Facultad1_idx` (`Facultad_idFacultad` ASC),
  CONSTRAINT `fk_Programa_Facultad1`
    FOREIGN KEY (`Facultad_idFacultad`)
    REFERENCES `VotacionesUnimag`.`Facultad` (`idFacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VotacionesUnimag`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VotacionesUnimag`.`Estado` (
  `idEstado` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(245) NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VotacionesUnimag`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VotacionesUnimag`.`Rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(245) NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VotacionesUnimag`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VotacionesUnimag`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `segundoNombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `segundoApellido` VARCHAR(45) NULL,
  `codigo` VARCHAR(45) NULL,
  `identificacion` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `Programa_idPrograma` INT NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  `Rol_idRol` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `identificacion_UNIQUE` (`identificacion` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_Usuario_Programa1_idx` (`Programa_idPrograma` ASC),
  INDEX `fk_Usuario_Estado1_idx` (`Estado_idEstado` ASC),
  INDEX `fk_Usuario_Rol1_idx` (`Rol_idRol` ASC),
  CONSTRAINT `fk_Usuario_Programa1`
    FOREIGN KEY (`Programa_idPrograma`)
    REFERENCES `VotacionesUnimag`.`Programa` (`idPrograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `VotacionesUnimag`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `VotacionesUnimag`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VotacionesUnimag`.`Puesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VotacionesUnimag`.`Puesto` (
  `idPuesto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(245) NULL,
  `Puestocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idPuesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VotacionesUnimag`.`Delegado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VotacionesUnimag`.`Delegado` (
  `idDelegado` INT NOT NULL,
  `Delegadocol` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idDelegado`),
  INDEX `fk_Delegado_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Delegado_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `VotacionesUnimag`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VotacionesUnimag`.`Dotacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VotacionesUnimag`.`Dotacion` (
  `idDotacion` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `Delegado_idDelegado` INT NOT NULL,
  PRIMARY KEY (`idDotacion`),
  INDEX `fk_Dotacion_Delegado1_idx` (`Delegado_idDelegado` ASC),
  CONSTRAINT `fk_Dotacion_Delegado1`
    FOREIGN KEY (`Delegado_idDelegado`)
    REFERENCES `VotacionesUnimag`.`Delegado` (`idDelegado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VotacionesUnimag`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VotacionesUnimag`.`Mesa` (
  `idMesa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `Puesto_idPuesto` INT NOT NULL,
  `Dotacion_idDotacion` INT NOT NULL,
  PRIMARY KEY (`idMesa`),
  INDEX `fk_Mesa_Puesto1_idx` (`Puesto_idPuesto` ASC),
  INDEX `fk_Mesa_Dotacion1_idx` (`Dotacion_idDotacion` ASC),
  CONSTRAINT `fk_Mesa_Puesto1`
    FOREIGN KEY (`Puesto_idPuesto`)
    REFERENCES `VotacionesUnimag`.`Puesto` (`idPuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mesa_Dotacion1`
    FOREIGN KEY (`Dotacion_idDotacion`)
    REFERENCES `VotacionesUnimag`.`Dotacion` (`idDotacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VotacionesUnimag`.`Votante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VotacionesUnimag`.`Votante` (
  `idVotante` INT NOT NULL,
  `idCertificado` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Mesa_idMesa` INT NOT NULL,
  PRIMARY KEY (`idVotante`),
  INDEX `fk_Votante_Usuario1_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_Votante_Mesa1_idx` (`Mesa_idMesa` ASC),
  CONSTRAINT `fk_Votante_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `VotacionesUnimag`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Votante_Mesa1`
    FOREIGN KEY (`Mesa_idMesa`)
    REFERENCES `VotacionesUnimag`.`Mesa` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VotacionesUnimag`.`Certificado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VotacionesUnimag`.`Certificado` (
  `idCertificado` INT NOT NULL AUTO_INCREMENT,
  `Votante_idVotante` INT NOT NULL,
  PRIMARY KEY (`idCertificado`),
  INDEX `fk_Certificado_Votante1_idx` (`Votante_idVotante` ASC),
  CONSTRAINT `fk_Certificado_Votante1`
    FOREIGN KEY (`Votante_idVotante`)
    REFERENCES `VotacionesUnimag`.`Votante` (`idVotante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VotacionesUnimag`.`Viatico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VotacionesUnimag`.`Viatico` (
  `idViatico` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idViatico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VotacionesUnimag`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VotacionesUnimag`.`Login` (
  `idLogin` INT NOT NULL,
  `password` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idLogin`, `Usuario_idUsuario`),
  INDEX `fk_Login_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Login_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `VotacionesUnimag`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VotacionesUnimag`.`Jurado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VotacionesUnimag`.`Jurado` (
  `idJurado` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Mesa_idMesa` INT NOT NULL,
  PRIMARY KEY (`idJurado`),
  INDEX `fk_Jurado_Usuario1_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_Jurado_Mesa1_idx` (`Mesa_idMesa` ASC),
  CONSTRAINT `fk_Jurado_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `VotacionesUnimag`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jurado_Mesa1`
    FOREIGN KEY (`Mesa_idMesa`)
    REFERENCES `VotacionesUnimag`.`Mesa` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VotacionesUnimag`.`Testigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VotacionesUnimag`.`Testigo` (
  `idTestigo` INT NOT NULL,
  `Testigocol` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idTestigo`),
  INDEX `fk_Testigo_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Testigo_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `VotacionesUnimag`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VotacionesUnimag`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VotacionesUnimag`.`Administrador` (
  `idAdministrador` INT NOT NULL,
  `Administradorcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VotacionesUnimag`.`Logistica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VotacionesUnimag`.`Logistica` (
  `idLogistica` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idLogistica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VotacionesUnimag`.`Bono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VotacionesUnimag`.`Bono` (
  `Viatico_idViatico` INT NOT NULL,
  `Jurado_idJurado` INT NOT NULL,
  PRIMARY KEY (`Viatico_idViatico`, `Jurado_idJurado`),
  INDEX `fk_Viatico_has_Jurado_Jurado1_idx` (`Jurado_idJurado` ASC),
  INDEX `fk_Viatico_has_Jurado_Viatico1_idx` (`Viatico_idViatico` ASC),
  CONSTRAINT `fk_Viatico_has_Jurado_Viatico1`
    FOREIGN KEY (`Viatico_idViatico`)
    REFERENCES `VotacionesUnimag`.`Viatico` (`idViatico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viatico_has_Jurado_Jurado1`
    FOREIGN KEY (`Jurado_idJurado`)
    REFERENCES `VotacionesUnimag`.`Jurado` (`idJurado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
