-- MySQL Script generated by MySQL Workbench
-- mar 10 abr 2018 00:40:55 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistema_votacion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_votacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_votacion` DEFAULT CHARACTER SET utf8 ;
USE `sistema_votacion` ;

-- -----------------------------------------------------
-- Table `sistema_votacion`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_votacion`.`usuario` (
  `cedula` INT NOT NULL,
  `contrasena` VARCHAR(20) NOT NULL,
  `tipo` ENUM('jurado', 'votante') NOT NULL,
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `usuario` (`cedula`, `contrasena`, `tipo`) VALUES 
('11110000', '1100', 'jurado'),
('11112222', '1122', 'jurado'),
('11223344', '1234', 'votante'),
('22224444', '2244', 'votante');
